package com.thermetery.boardview

import android.graphics.Color
import android.graphics.Typeface
import android.os.Bundle
import android.util.TypedValue
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.TextView
import androidx.activity.ComponentActivity

/**
 * Read-only "Third-party licenses" screen showing the consolidated notice
 * asset generated by packaging/collect_android_licenses.py (regenerate and
 * recommit it whenever the Chaquopy requirements or bundled runtime change).
 * Reachable from the key-management screen's footer.
 */
class LicensesActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val d = resources.displayMetrics.density
        fun dp(v: Int) = (v * d).toInt()

        val root = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            setBackgroundColor(Color.parseColor("#0d1024"))
            setPadding(dp(20), dp(24), dp(20), dp(24))
        }

        root.addView(TextView(this).apply {
            text = "Third-party licenses"
            setTextColor(Color.WHITE)
            setTextSize(TypedValue.COMPLEX_UNIT_SP, 22f)
            setPadding(0, 0, 0, dp(12))
        })

        val body = TextView(this).apply {
            typeface = Typeface.MONOSPACE
            setTextColor(Color.parseColor("#cdd6ff"))
            setTextSize(TypedValue.COMPLEX_UNIT_SP, 11f)
            setTextIsSelectable(true)
            text = "Loading…"
        }
        root.addView(body)

        setContentView(ScrollView(this).apply {
            setBackgroundColor(Color.parseColor("#0d1024"))
            addView(root)
        })

        // ~100 KB of text; read it off the UI thread.
        Thread {
            val text = try {
                assets.open("third_party_licenses.txt")
                    .use { it.readBytes().toString(Charsets.UTF_8) }
            } catch (t: Throwable) {
                "Could not load the license file: ${t.message}"
            }
            runOnUiThread { body.text = text }
        }.start()
    }
}
