#!/bin/bash
# Xcode build phase: copy the shared JS renderer (owned by the renderer agent
# — never fork it) from the Android assets folder, plus the iOS-specific
# third-party license text (generated by packaging/collect_ios_licenses.py),
# into the app bundle at $APP/web/. The iOS shell serves viewer.html from
# there via WKWebView.loadFileURL.
set -euo pipefail

REPO_ROOT="$(cd "$PROJECT_DIR/.." && pwd)"
SRC="$REPO_ROOT/android/app/src/main/assets"
DEST="$CODESIGNING_FOLDER_PATH/web"

ASSETS=(viewer.html viewer.js viewer.css)

for a in "${ASSETS[@]}"; do
    if [ ! -f "$SRC/$a" ]; then
        echo "error: stage_assets.sh: $SRC/$a is missing — the shared renderer" \
             "assets live in the Android tree (contract: docs/android_contract.md §1)." >&2
        exit 1
    fi
done
if [ ! -f "$PROJECT_DIR/third_party_licenses.txt" ]; then
    echo "error: stage_assets.sh: ios/third_party_licenses.txt is missing —" \
         "run packaging/collect_ios_licenses.py and commit the result." >&2
    exit 1
fi

rm -rf "$DEST"
mkdir -p "$DEST"
for a in "${ASSETS[@]}"; do
    cp "$SRC/$a" "$DEST/$a"
done
cp "$PROJECT_DIR/third_party_licenses.txt" "$DEST/third_party_licenses.txt"
echo "Staged ${#ASSETS[@]} web assets + iOS license notices into web/"
