#!/usr/bin/env python3
"""Consolidate the iOS app's third-party license material into one asset.

Writes ``ios/third_party_licenses.txt`` from explicit sources and nothing
else — the iOS sibling of collect_android_licenses.py:

1. an allowlist of public project license files (LICENSE, parser notices);
2. committed copies under ``LICENSES/ios/`` of the licenses for what the
   app bundle actually embeds: numpy (the BeeWare-built wheel) and the
   Python-Apple-support runtime with its bundled libraries (CPython PSF,
   OpenSSL, BZip2, libFFI, XZ, mpdecimal);
3. component versions read from ``ios/vendor/VERSIONS`` when the vendor
   tree is present (ios/fetch_deps.sh), so the banner matches the build.

Like the other collectors, this script never walks the repository and
refuses to read anything under ``private/``. Re-run it after bumping
Python-Apple-support or the numpy wheel in ios/fetch_deps.sh, then commit
the regenerated asset (ios/stage_assets.sh copies it into the bundle).
"""

from __future__ import annotations

from pathlib import Path
import sys
from typing import Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "ios" / "third_party_licenses.txt"
VERSIONS_FILE = REPO_ROOT / "ios" / "vendor" / "VERSIONS"

# Project material relevant to the iOS app (desktop-only entries such as
# PyOpenGL/Tcl/Tk are deliberately absent; the kernels' MIT notices are
# required because xzz/rc6 ship compiled into the app).
PROJECT_SECTIONS: Tuple[Tuple[str, str], ...] = (
    ("Thermetery Boardview", "LICENSE"),
    ("Third-party notices (parsers)", "THIRD_PARTY_NOTICES.md"),
    ("OpenBoardView (format research, RC6/FZ port)", "LICENSES/OpenBoardView-MIT.txt"),
    ("dhuertas DES (XZZ decryption)", "LICENSES/dhuertas-DES-MIT.txt"),
)

# Everything the bundle embeds beyond our own code. The version notes in
# the banner come from ios/vendor/VERSIONS; the license texts are committed
# copies so this collector works on a fresh checkout without vendor/.
STATIC_SECTIONS: Tuple[Tuple[str, str], ...] = (
    ("CPython (embedded via Python-Apple-support) - PSF License 2.0",
     "LICENSES/android/CPython-PSF-2.0.txt"),
    ("Python-Apple-support (BeeWare) - MIT",
     "LICENSES/ios/Python-Apple-support-MIT.txt"),
    ("numpy - BSD 3-Clause", "LICENSES/ios/numpy-BSD-3.txt"),
    ("numpy.random bundled algorithm licenses",
     "LICENSES/numpy-random-licenses.md"),
    ("OpenSSL 3.x - Apache License 2.0", "LICENSES/android/Apache-2.0.txt"),
    ("BZip2", "LICENSES/android/bzip2-1.0.8.txt"),
    ("libFFI - MIT", "LICENSES/android/libffi-MIT.txt"),
    ("XZ Utils (liblzma) - 0BSD", "LICENSES/ios/XZ-0BSD.txt"),
    ("mpdecimal (libmpdec) - Simplified BSD", "LICENSES/ios/mpdecimal-BSD-2.txt"),
)

DIVIDER = "=" * 78


def read_text(rel: str) -> str:
    path = REPO_ROOT / rel
    if "private" in path.parts:
        raise SystemExit(f"refusing to read {rel}: private/ is off-limits")
    if not path.is_file():
        raise SystemExit(
            f"collect_ios_licenses: missing {rel} — the explicit source list "
            f"must match the repository; do not remove entries silently."
        )
    return path.read_text(encoding="utf-8", errors="replace").strip()


def component_versions() -> str:
    if not VERSIONS_FILE.is_file():
        return "(component versions: run ios/fetch_deps.sh and re-run to embed them)"
    return VERSIONS_FILE.read_text(encoding="utf-8").strip()


def main() -> int:
    sections = []
    for title, rel in PROJECT_SECTIONS + STATIC_SECTIONS:
        sections.append(f"{DIVIDER}\n{title}\n{DIVIDER}\n\n{read_text(rel)}\n")

    banner = (
        f"{DIVIDER}\n"
        "Thermetery Boardview for iOS - third-party licenses\n"
        "Generated by packaging/collect_ios_licenses.py - DO NOT EDIT.\n"
        "Re-run after bumping Python-Apple-support or numpy, then commit.\n"
        f"{DIVIDER}\n\n"
        "Embedded runtime components (ios/vendor/VERSIONS):\n"
        f"{component_versions()}\n"
        "numpy: 1.26.2 (BeeWare iOS wheel)\n\n"
    )
    OUTPUT.write_text(banner + "\n".join(sections), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} "
          f"({OUTPUT.stat().st_size} bytes, {len(sections)} sections)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
